name: Publish Docker Latest
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Docker
      run: docker build -f Dockerfile -t "joplin-archlinux:${{ github.run_id}}" joplin/
    - name: Build Joplin
      run: docker run -t "joplin-archlinux:${{ github.run_id}}"